// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabajoFinalGrupo6DBP;

#nullable disable

namespace TrabajoFinalGrupo6DBP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118214921_CrearBDTrabajoFinalGrupo6DBP")]
    partial class CrearBDTrabajoFinalGrupo6DBP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.CitaMedica", b =>
                {
                    b.Property<int>("Id_CitaMedica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CitaMedica"));

                    b.Property<string>("Estado_CitaMedica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_CitaMedica")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora_CitaMedica")
                        .HasColumnType("time");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id_CitaMedica");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Citas_Medicas");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.Especialidad", b =>
                {
                    b.Property<int>("Id_Especialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Especialidad"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado_Especialidad")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre_Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Especialidad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.HorarioMedico", b =>
                {
                    b.Property<int>("Id_Horario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Horario"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Hora_Fin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Hora_Inicio")
                        .HasColumnType("time");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.HasKey("Id_Horario");

                    b.HasIndex("MedicoId");

                    b.ToTable("Horarios_Medicos");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.Medico", b =>
                {
                    b.Property<int>("Id_Medico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Medico"));

                    b.Property<string>("Correo_Medico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI_Medico")
                        .HasColumnType("int");

                    b.Property<bool>("Estado_Medico")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Especialidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Completo_Medico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono_Medico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Medico");

                    b.HasIndex("Id_Especialidad");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.Paciente", b =>
                {
                    b.Property<int>("Id_Paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Paciente"));

                    b.Property<string>("Contrasenia_Paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo_Paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI_Paciente")
                        .HasColumnType("int");

                    b.Property<string>("Direccion_Paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Nacimiento_Paciente")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Completo_Paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono_Paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Paciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Apellidos_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasenia_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo_Electronico_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombres_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.CitaMedica", b =>
                {
                    b.HasOne("TrabajoFinalGrupo6DBP.Models.Medico", "Medico")
                        .WithMany("CitasMedicas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrabajoFinalGrupo6DBP.Models.Paciente", "Paciente")
                        .WithMany("CitasMedicas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.HorarioMedico", b =>
                {
                    b.HasOne("TrabajoFinalGrupo6DBP.Models.Medico", "Medico")
                        .WithMany("Horarios")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.Medico", b =>
                {
                    b.HasOne("TrabajoFinalGrupo6DBP.Models.Especialidad", "Especialidad")
                        .WithMany("Medicos")
                        .HasForeignKey("Id_Especialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.Especialidad", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.Medico", b =>
                {
                    b.Navigation("CitasMedicas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("TrabajoFinalGrupo6DBP.Models.Paciente", b =>
                {
                    b.Navigation("CitasMedicas");
                });
#pragma warning restore 612, 618
        }
    }
}
